/**
 * Cursor 平台适配器
 * 生成 .cursor/rules/*.mdc 文件
 */

import { 
  PlatformAdapter, 
  RoleExportData, 
  FlavorExportData, 
  PlatformExportConfig 
} from './base-adapter.js';
import { globalAdapterRegistry } from './base-adapter.js';

export class CursorAdapter extends PlatformAdapter {
  constructor() {
    super('cursor', ['zh', 'en']);
  }

  /**
   * 导出角色为 .mdc 格式
   */
  exportRole(role: RoleExportData, _config: PlatformExportConfig): string {
    const flavorOverlay = this.buildFlavorOverlay(role.compatibleFlavors);
    
    return `---
# Cursor Rule File
# Generated by PUAX Platform Adapter
# Role: ${role.name}
# Version: ${role.metadata.version}

description: ${role.description}
globs: "**/*"
alwaysApply: false
---

# PUAX Role: ${role.name}

## 角色定位
${role.description}

## 触发条件
${role.triggerConditions.map(c => `- ${c}`).join('\n')}

## 适用任务类型
${role.taskTypes.map(t => `- ${t}`).join('\n')}

## 系统提示词

${role.systemPrompt}

${flavorOverlay}

## 元数据
- 语气: ${role.metadata.tone}
- 强度: ${role.metadata.intensity}
- 版本: ${role.metadata.version}

---
*此文件由 PUAX 自动生成 - https://puax.net*
`;
  }

  /**
   * Cursor 不直接支持风味文件，将风味叠加到角色中
   */
  exportFlavor(flavor: FlavorExportData, _config: PlatformExportConfig): string {
    // Cursor 使用 flavor 作为旁白叠加
    return `---
description: "PUAX Flavor: ${flavor.name}"
globs: "**/*"
alwaysApply: false
---

# ${flavor.name} 风味叠加

${flavor.description}

## 关键词
${flavor.keywords.map(k => `- ${k}`).join('\n')}

## 开场白
${flavor.rhetoric.opening.map(r => `> ${r}`).join('\n\n')}

## 强调词汇
${flavor.rhetoric.emphasis.map(e => `- **${e}**`).join('\n')}
`;
  }

  /**
   * 生成 Cursor 配置
   */
  generateConfig(roles: RoleExportData[], _config: PlatformExportConfig): string {
    const configObj = {
      name: 'PUAX for Cursor',
      version: '2.0.0',
      description: 'AI Agent 激励系统 - Cursor 版本',
      roles: roles.map(r => ({
        id: r.id,
        name: r.name,
        file: `${r.id}.mdc`,
        globs: ['**/*']
      })),
      installation: {
        description: '将 .mdc 文件复制到 .cursor/rules/ 目录',
        autoApply: false
      }
    };

    return JSON.stringify(configObj, null, 2);
  }

  /**
   * 构建风味叠加文本
   */
  private buildFlavorOverlay(flavorIds: string[]): string {
    if (!flavorIds || flavorIds.length === 0) {
      return '';
    }

    return `
## 兼容风味叠加
此角色支持以下大厂风味叠加：
${flavorIds.map(id => `- ${id}`).join('\n')}

使用时，在对话中指定风味，例如："使用阿里风味"。
`;
  }

  protected getFileExtension(): string {
    return 'mdc';
  }

  protected getConfigFileName(): string {
    return 'cursor-config.json';
  }

  protected supportsFlavorExport(): boolean {
    return true;
  }

  protected getFlavorFileName(flavor: FlavorExportData): string {
    return `flavor-${flavor.id}.mdc`;
  }
}

// 注册适配器
globalAdapterRegistry.register(new CursorAdapter());
