/**
 * PUAX Hook 模板（平台适配器共享）
 *
 * 供 claude-code / cursor / opencode 等适配器生成原生 hook 产物。
 * 模板设计借鉴 obra/superpowers 的 polyglot 模式（Hook机制演进方案.md 决策 3）：
 * - 事件一律走 `puax-mcp-server hook <event>` 单一通路（引擎共享层）；
 * - 优雅降级：任何失败输出 {} 且退出 0，绝不中断宿主会话；
 * - 无扩展名脚本规避 Claude Code 在 Windows 上对 .sh 自动前置 bash 的行为。
 */

/** node 入口：宿主直接执行 `node hooks/hook.js <event> [args]` */
export const HOOK_JS = `#!/usr/bin/env node
/**
 * PUAX hook 入口（由 puax 平台适配器生成，勿手改）
 * 用法: node hooks/hook.js <事件> [选项]   →  输出宿主 JSON 到 stdout
 * 依赖: 已安装 puax-mcp-server（npx puax-mcp-server hook ...）
 *
 * 经 mainHookCliWithStdin 入口：Claude Code 等宿主在事件时经 stdin
 * 传入 { tool_name, tool_input, tool_response, session_id }，
 * 缺失的 CLI 参数会从 stdin 载荷自动补充（显式参数优先）。
 */
let main;
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  main = require('puax-mcp-server/build/cli/hook-cli.js').mainHookCliWithStdin;
} catch {
  // 未安装依赖：优雅降级，不中断宿主
  process.stdout.write('{}\\n');
  process.exit(0);
}
main(process.argv.slice(2));
`;

/** polyglot 分发器：同一文件兼容 cmd.exe 与 bash（superpowers 同款模式） */
export const RUN_HOOK_CMD = `: << 'CMDBLOCK'
@echo off
REM PUAX polyglot hook dispatcher (generated by puax platform adapter)
REM Windows: cmd.exe runs this batch section, which calls node.
REM Unix: bash treats the whole batch section as a no-op heredoc.
REM NOTE: keep REM comments ASCII-only - cmd.exe parses this file with the
REM system codepage; non-ASCII bytes corrupt batch parsing.
if "%~1"=="" exit /b 0
where node >nul 2>nul
if %ERRORLEVEL% neq 0 exit /b 0
node "%~dp0hook.js" %*
exit /b 0
CMDBLOCK

# Unix: run the node entry directly
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
command -v node >/dev/null 2>&1 || exit 0
exec node "\${SCRIPT_DIR}/hook.js" "$@"
`;

/** 无扩展名事件脚本（宿主可能要求脚本文件；内容即转发到 hook.js） */
export function eventScript(event: string): string {
  return `#!/usr/bin/env bash
# PUAX hook: ${event}（由 puax 平台适配器生成）
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
exec node "\${SCRIPT_DIR}/hook.js" ${event} "$@"
`;
}

/**
 * opencode 进程内插件（Shape B，v1）。
 * 仿 obra/superpowers 的 .opencode/plugins/superpowers.js：
 * 每个 agent step 自动触发，经 CLI 单通路调检测引擎。
 */
export function opencodePlugin({ marker }: { marker: string }): string {
  return `/**
 * PUAX plugin for OpenCode.ai（由 puax 平台适配器生成）
 * Shape B 进程内插件：每个 agent step 自动触发，经
 * \`puax-mcp-server hook\` 单通路调用检测引擎（引擎共享层）。
 * 优雅降级：CLI 不可用时静默跳过，不干扰会话。
 */
import { execFileSync } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const MARKER = ${JSON.stringify(marker)};

// Windows 上 npx 是 npx.cmd；execFileSync 不经 shell，不解析 .cmd 扩展名
const NPX_BIN = process.platform === 'win32' ? 'npx.cmd' : 'npx';

// 模块级缓存：同一会话只注入一次（避免每 step 重复 spawn）
let _injectedSession = null;

function runHook(event, extraArgs = []) {
  const args = ['puax-mcp-server', 'hook', event, '--harness', 'sdk', ...extraArgs];
  try {
    const stdout = execFileSync(NPX_BIN, args, {
      encoding: 'utf8',
      timeout: 5000,
      stdio: ['ignore', 'pipe', 'ignore']
    });
    return JSON.parse(stdout || '{}');
  } catch {
    return {};
  }
}

export const PuaxPlugin = async () => {
  return {
    config: async (config) => {
      // 注册技能目录（复用 PUAX 导出的 skills/，无 symlink 需要）
      const skillsDir = path.resolve(__dirname, '../skills');
      config.skills = config.skills || {};
      config.skills.paths = config.skills.paths || [];
      if (!config.skills.paths.includes(skillsDir)) {
        config.skills.paths.push(skillsDir);
      }
    },

    'experimental.chat.messages.transform': async (_input, output) => {
      if (!output.messages || !output.messages.length) return;
      const firstUser = output.messages.find(m => m.info?.role === 'user');
      if (!firstUser || !firstUser.parts || !firstUser.parts.length) return;

      // 去重守卫：已注入则跳过
      if (firstUser.parts.some(p => p.type === 'text' && p.text.includes(MARKER))) return;

      // 会话恢复上下文（仅一次）
      let text = null;
      if (_injectedSession !== _input.sessionID) {
        const res = runHook('SessionStart', ['--session-id', _input.sessionID || 'opencode']);
        _injectedSession = _input.sessionID;
        if (res.hookSpecificOutput?.additionalContext || res.additionalContext || res.additional_context) {
          text = res.hookSpecificOutput?.additionalContext || res.additionalContext || res.additional_context;
        }
      }

      // 每轮用户消息检测（挫折/放弃语言）
      if (!text) {
        const userText = firstUser.parts
          .filter(p => p.type === 'text')
          .map(p => p.text || '')
          .join(' ');
        if (userText.trim()) {
          const res = runHook('UserPromptSubmit', ['--session-id', _input.sessionID || 'opencode', '--message', userText]);
          text = res.hookSpecificOutput?.additionalContext || res.additionalContext || res.additional_context || null;
        }
      }

      if (!text) return;

      const ref = firstUser.parts[0];
      firstUser.parts.unshift({ ...ref, type: 'text', text });
    }
  };
};
`;
}

/** 默认 marker：用于去重守卫 */
export const DEFAULT_MARKER = '<EXTREMELY_IMPORTANT>';
