/**
 * Kiro 平台适配器
 * 生成 .kiro/steering/*.md 文件
 */

import { 
  PlatformAdapter, 
  RoleExportData, 
  FlavorExportData, 
  PlatformExportConfig,
  globalAdapterRegistry
} from './base-adapter.js';

export class KiroAdapter extends PlatformAdapter {
  constructor() {
    super('kiro', ['zh', 'en']);
  }

  /**
   * 导出角色为 Markdown 格式 (Steering)
   */
  exportRole(role: RoleExportData, config: PlatformExportConfig): string {
    return `---
# Kiro Steering File
# Generated by PUAX Platform Adapter
# Role: ${role.name}
# Version: ${role.metadata.version}
---

# PUAX Role: ${role.name}

## 角色定位
${role.description}

## 适用场景
${role.taskTypes.map(t => `- ${t}`).join('\n')}

## 触发条件
${role.triggerConditions.map(c => `- ${c}`).join('\n')}

## 系统提示词

${role.systemPrompt}

## 元数据
- 语气: ${role.metadata.tone}
- 强度: ${role.metadata.intensity}
- 版本: ${role.metadata.version}

---
*此文件由 PUAX 自动生成 - https://puax.net*
`;
  }

  /**
   * 导出风味
   */
  exportFlavor(flavor: FlavorExportData, config: PlatformExportConfig): string {
    return `---
# PUAX Flavor: ${flavor.name}
---

# ${flavor.name} 风味叠加

${flavor.description}

## 核心关键词
${flavor.keywords.map(k => `- ${k}`).join('\n')}

## 修辞表达

### 开场白
${flavor.rhetoric.opening.map(r => `> ${r}`).join('\n\n')}

### 结束语
${flavor.rhetoric.closing.map(r => `> ${r}`).join('\n\n')}

### 强调词汇
${flavor.rhetoric.emphasis.map(e => `- **${e}**`).join('\n')}

## 使用方式
在对话中引用此风味，例如：
- "请用${flavor.name}重新分析"
- "切换到${flavor.name}模式"
`;
  }

  /**
   * 生成 Kiro 配置
   */
  generateConfig(roles: RoleExportData[], config: PlatformExportConfig): string {
    const configObj = {
      name: 'PUAX for Kiro',
      version: '2.0.0',
      description: 'AI Agent 激励系统 - Kiro Steering 版本',
      type: 'steering',
      roles: roles.map(r => ({
        id: r.id,
        name: r.name,
        file: `${r.id}.md`,
        autoApply: false
      })),
      installation: {
        description: '将 .md 文件复制到 .kiro/steering/ 目录',
        path: '.kiro/steering/',
        autoApply: false
      }
    };

    return JSON.stringify(configObj, null, 2);
  }

  protected getFileExtension(): string {
    return 'md';
  }

  protected getConfigFileName(): string {
    return 'kiro-config.json';
  }

  protected supportsFlavorExport(): boolean {
    return true;
  }

  protected getRoleFileName(role: RoleExportData): string {
    return `${role.id}.md`;
  }

  protected getFlavorFileName(flavor: FlavorExportData): string {
    return `flavor-${flavor.id}.md`;
  }
}

// 注册适配器
globalAdapterRegistry.register(new KiroAdapter());
