/**
 * 通用 SKILL.md 平台适配器工厂
 * 用于 Codex CLI、OpenCode、OpenClaw、Antigravity、Trae、pi 等 skill 安装型平台
 */

import {
  PlatformAdapter,
  RoleExportData,
  FlavorExportData,
  PlatformExportConfig,
  globalAdapterRegistry,
} from './base-adapter.js';
import { applyPipEdition, type SupportedLanguage } from '../core/i18n-en.js';

export interface SkillPlatformOptions {
  platformName: string;
  roleSubdir: string;
  supportedLanguages?: SupportedLanguage[];
  installPathHint: string;
}

export class SkillMdPlatformAdapter extends PlatformAdapter {
  private roleSubdir: string;
  private installPathHint: string;

  constructor(options: SkillPlatformOptions) {
    super(options.platformName, options.supportedLanguages ?? ['zh', 'en']);
    this.roleSubdir = options.roleSubdir;
    this.installPathHint = options.installPathHint;
  }

  exportRole(role: RoleExportData, config: PlatformExportConfig): string {
    const lang = (config.language ?? 'zh') as SupportedLanguage;
    let body = role.systemPrompt;
    if (lang === 'en') {
      body = applyPipEdition(body, role.name, role.description);
    }

    const desc = lang === 'en'
      ? `PUAX role: ${role.name} — ${role.description}`
      : `PUAX 角色：${role.name} — ${role.description}`;

    return `---
name: puax-${role.id}
description: "${desc.replace(/"/g, '\\"')}"
license: MIT
puax:
  platform: ${this.platformName}
  role_id: ${role.id}
  version: ${role.metadata.version}
  language: ${lang}
---

# PUAX · ${role.name}

${body}

## ${lang === 'en' ? 'Metadata' : '元数据'}
- ${lang === 'en' ? 'Tone' : '语气'}: ${role.metadata.tone}
- ${lang === 'en' ? 'Intensity' : '强度'}: ${role.metadata.intensity}
- Category: ${role.category}

---
*Generated by PUAX v3.5 — https://github.com/linkerlin/PUAX*
`;
  }

  exportFlavor(flavor: FlavorExportData, config: PlatformExportConfig): string {
    const lang = config.language === 'en' ? 'en' : 'zh';
    return `---
name: puax-flavor-${flavor.id}
description: "PUAX flavor overlay: ${flavor.name}"
license: MIT
---

# ${flavor.name}

${flavor.description}

${flavor.keywords.map(k => `- ${k}`).join('\n')}
`;
  }

  generateConfig(roles: RoleExportData[], _config: PlatformExportConfig): string {
    return JSON.stringify({
      name: `PUAX for ${this.platformName}`,
      version: '3.5.0',
      platform: this.platformName,
      install_hint: this.installPathHint,
      roles: roles.map(r => ({
        id: r.id,
        path: `${this.roleSubdir}/${r.id}/SKILL.md`,
      })),
      mcp_alternative: 'npx puax-mcp-server',
    }, null, 2);
  }

  protected getRoleFileName(role: RoleExportData): string {
    return `${this.roleSubdir}/${role.id}/SKILL.md`;
  }

  protected getFlavorFileName(flavor: FlavorExportData): string {
    return `${this.roleSubdir}/flavors/${flavor.id}/SKILL.md`;
  }

  protected getConfigFileName(): string {
    return `${this.platformName}-puax-config.json`;
  }

  protected getFileExtension(): string {
    return 'md';
  }

  protected supportsFlavorExport(): boolean {
    return true;
  }
}

const EXTENDED_PLATFORMS: SkillPlatformOptions[] = [
  {
    platformName: 'codex',
    roleSubdir: 'skills',
    installPathHint: 'Copy skills/ to ~/.codex/skills/ or use npx skills add',
  },
  {
    platformName: 'opencode',
    roleSubdir: 'skills',
    installPathHint: 'Copy skills/ to ~/.config/opencode/skills/',
  },
  {
    platformName: 'openclaw',
    roleSubdir: 'skills',
    installPathHint: 'Copy skills/ to OpenClaw skills directory',
  },
  {
    platformName: 'antigravity',
    roleSubdir: 'skills',
    installPathHint: 'Import skills/ into Google Antigravity agent config',
  },
  {
    platformName: 'trae',
    roleSubdir: 'skills',
    installPathHint: 'Copy skills/ to Trae agent skills path (see trae/INSTALL.md)',
  },
  {
    platformName: 'pi',
    roleSubdir: 'package/skills',
    installPathHint: 'pi install ./package or copy to ~/.pi/agent/extensions/puax/',
  },
];

export function registerSkillPlatformAdapters(): void {
  for (const opts of EXTENDED_PLATFORMS) {
    globalAdapterRegistry.register(new SkillMdPlatformAdapter(opts));
  }
}

registerSkillPlatformAdapters();

export const EXTENDED_PLATFORM_NAMES = EXTENDED_PLATFORMS.map(p => p.platformName);
