"use strict";
/**
 * VSCode Copilot 平台适配器
 * 生成 .github/copilot-instructions.md 和 prompts
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VSCodeAdapter = void 0;
const base_adapter_js_1 = require("./base-adapter.js");
class VSCodeAdapter extends base_adapter_js_1.PlatformAdapter {
    constructor() {
        super('vscode', ['zh', 'en']);
    }
    /**
     * 导出角色为 Markdown 格式
     */
    exportRole(role, config) {
        const lang = config.language || 'zh';
        return `# PUAX Role: ${role.name}

## 描述
${role.description}

## 使用场景
${role.taskTypes.map(t => `- ${t}`).join('\n')}

## 激活条件
${role.triggerConditions.map(c => `- ${c}`).join('\n')}

## 角色设定

${role.systemPrompt}

---
*Generated by PUAX - https://puax.net*
`;
    }
    /**
     * 导出风味
     */
    exportFlavor(flavor, config) {
        return `# ${flavor.name} 风味指南

${flavor.description}

## 核心关键词
${flavor.keywords.map(k => `- ${k}`).join('\n')}

## 表达方式

### 开场白
${flavor.rhetoric.opening.map(r => `- "${r}"`).join('\n')}

### 结束语
${flavor.rhetoric.closing.map(r => `- "${r}"`).join('\n')}

### 强调词汇
${flavor.rhetoric.emphasis.map(e => `- **${e}**`).join('\n')}

## 使用方式
在对话中引用此风味，例如：
- "请用${flavor.name}重新分析"
- "切换到${flavor.name}模式"
`;
    }
    /**
     * 生成 VSCode Copilot 配置
     */
    generateConfig(roles, config) {
        // 生成主 instructions 文件
        const mainInstructions = this.generateMainInstructions(roles);
        // 生成 prompts 配置
        const promptsConfig = {
            version: '2.0.0',
            name: 'PUAX for VSCode Copilot',
            description: 'AI Agent 激励系统',
            instructions: roles.map(r => ({
                id: r.id,
                name: r.name,
                description: r.description,
                file: `instructions/${r.id}.instructions.md`,
                globs: r.taskTypes.map(t => this.getGlobForTaskType(t))
            })),
            prompts: roles.map(r => ({
                id: r.id,
                name: r.name,
                description: `激活 ${r.name} 角色`,
                file: `prompts/${r.id}.prompt.md`
            }))
        };
        return JSON.stringify(promptsConfig, null, 2);
    }
    /**
     * 生成主 instructions 文件内容
     */
    generateMainInstructions(roles) {
        return `# PUAX - AI Agent 激励系统

## 什么是 PUAX？

PUAX 是一个专为 AI Agent 设计的激励系统，通过权威角色、稀缺场景、竞争对象等心理学机制，提升 AI 的问题解决能力和主动性。

## 可用角色

${roles.map(r => `### ${r.name}
- **描述**: ${r.description}
- **适用**: ${r.taskTypes.join(', ')}
- **触发**: ${r.triggerConditions.join(', ')}
`).join('\n')}

## 使用方法

1. **手动激活**: 在 Copilot Chat 中输入 "/puax [角色名]"
2. **自动触发**: 当检测到特定模式时自动建议
3. **风味叠加**: 指定大厂风味改变表达方式

## 快速参考

| 角色 | 用途 | 激活命令 |
|------|------|---------|
${roles.slice(0, 10).map(r => `| ${r.name} | ${r.taskTypes[0] || '通用'} | /puax ${r.id} |`).join('\n')}

---
*了解更多: https://puax.net*
`;
    }
    /**
     * 根据任务类型获取 glob 模式
     */
    getGlobForTaskType(taskType) {
        const globMap = {
            'debugging': '**/*.{js,ts,py,java,c,cpp}',
            'coding': '**/*.{js,ts,jsx,tsx,py,java}',
            'planning': '**/README.md,**/docs/**/*.md',
            'review': '**/*.{js,ts,py}',
            'testing': '**/*.test.{js,ts},**/*.spec.{js,ts}'
        };
        return globMap[taskType] || '**/*';
    }
    /**
     * VSCode 导出需要特殊处理，创建多个文件
     */
    async export(roles, flavors, config) {
        const result = {
            success: true,
            exportedFiles: [],
            errors: [],
            warnings: []
        };
        try {
            // 创建目录结构
            const instructionsDir = (0, path_1.join)(config.outputPath, 'instructions');
            const promptsDir = (0, path_1.join)(config.outputPath, 'prompts');
            // 导出主 instructions
            const mainInstructions = this.generateMainInstructions(roles);
            const mainPath = (0, path_1.join)(config.outputPath, 'copilot-instructions.md');
            (0, fs_1.writeFileSync)(mainPath, mainInstructions, 'utf-8');
            result.exportedFiles.push(mainPath);
            // 导出每个角色的 instructions
            for (const role of roles) {
                const content = this.exportRole(role, config);
                const fileName = `${role.id}.instructions.md`;
                const filePath = (0, path_1.join)(instructionsDir, fileName);
                // 确保目录存在
                const dir = (0, path_1.dirname)(filePath);
                if (!(0, fs_1.existsSync)(dir)) {
                    (0, fs_1.mkdirSync)(dir, { recursive: true });
                }
                (0, fs_1.writeFileSync)(filePath, content, 'utf-8');
                result.exportedFiles.push(filePath);
                // 同时生成 prompt 版本
                const promptContent = this.generatePromptVersion(role);
                const promptPath = (0, path_1.join)(promptsDir, `${role.id}.prompt.md`);
                const promptDir = (0, path_1.dirname)(promptPath);
                if (!(0, fs_1.existsSync)(promptDir)) {
                    (0, fs_1.mkdirSync)(promptDir, { recursive: true });
                }
                (0, fs_1.writeFileSync)(promptPath, promptContent, 'utf-8');
                result.exportedFiles.push(promptPath);
            }
            // 生成配置
            const configContent = this.generateConfig(roles, config);
            const configPath = (0, path_1.join)(config.outputPath, 'puax-vscode-config.json');
            (0, fs_1.writeFileSync)(configPath, configContent, 'utf-8');
            result.exportedFiles.push(configPath);
        }
        catch (error) {
            const errorMsg = error instanceof Error ? error.message : 'Unknown error';
            result.errors.push(errorMsg);
            result.success = false;
        }
        return result;
    }
    /**
     * 生成 prompt 版本（简化版，用于快捷触发）
     */
    generatePromptVersion(role) {
        return `# /puax:${role.id}

激活 ${role.name} 角色。

${role.description}

## 快速使用
直接输入此 prompt 即可激活角色设定。

## 系统提示词

${role.systemPrompt.substring(0, 1000)}...

[完整提示词见 instructions/${role.id}.instructions.md]
`;
    }
    getFileExtension() {
        return 'md';
    }
    getConfigFileName() {
        return 'puax-vscode-config.json';
    }
    supportsFlavorExport() {
        return true;
    }
    getRoleFileName(role) {
        return `instructions/${role.id}.instructions.md`;
    }
}
exports.VSCodeAdapter = VSCodeAdapter;
// 注册适配器
const base_adapter_js_2 = require("./base-adapter.js");
const fs_1 = require("fs");
const path_1 = require("path");
base_adapter_js_2.globalAdapterRegistry.register(new VSCodeAdapter());
//# sourceMappingURL=vscode-adapter.js.map