/**
 * Windsurf 平台适配器
 * 生成 .windsurf/rules/*.md 文件
 */

import { 
  PlatformAdapter, 
  RoleExportData, 
  FlavorExportData, 
  PlatformExportConfig,
  globalAdapterRegistry
} from './base-adapter.js';

export class WindsurfAdapter extends PlatformAdapter {
  constructor() {
    super('windsurf', ['zh', 'en']);
  }

  /**
   * 导出角色为 Markdown 格式
   */
  exportRole(role: RoleExportData, _config: PlatformExportConfig): string {
    return `---
# Windsurf Rule File
# Generated by PUAX Platform Adapter
# Role: ${role.name}
# Version: ${role.metadata.version}
---

# PUAX Role: ${role.name}

## 描述
${role.description}

## 使用场景
${role.taskTypes.map(t => `- ${t}`).join('\n')}

## 激活条件
${role.triggerConditions.map(c => `- ${c}`).join('\n')}

## 角色设定

${role.systemPrompt}

## 兼容风味
${role.compatibleFlavors.map(f => `- ${f}`).join('\n')}

## 元数据
- 语气: ${role.metadata.tone}
- 强度: ${role.metadata.intensity}
- 版本: ${role.metadata.version}

---
*此文件由 PUAX 自动生成 - https://puax.net*
`;
  }

  /**
   * 导出风味
   */
  exportFlavor(flavor: FlavorExportData, _config: PlatformExportConfig): string {
    return `---
# PUAX Flavor: ${flavor.name}
---

# ${flavor.name} 风味指南

${flavor.description}

## 关键词
${flavor.keywords.map(k => `- ${k}`).join('\n')}

## 表达方式

### 开场
${flavor.rhetoric.opening.map(r => `- "${r}"`).join('\n')}

### 强调
${flavor.rhetoric.emphasis.map(e => `- **${e}**`).join('\n')}

## 使用
在 Windsurf 对话中引用："使用${flavor.name}"
`;
  }

  /**
   * 生成 Windsurf 配置
   */
  generateConfig(roles: RoleExportData[], _config: PlatformExportConfig): string {
    const configObj = {
      name: 'PUAX for Windsurf',
      version: '2.0.0',
      description: 'AI Agent 激励系统 - Windsurf 版本',
      type: 'rules',
      rules: roles.map(r => ({
        id: r.id,
        name: r.name,
        file: `${r.id}.md`,
        globs: ['**/*']
      })),
      installation: {
        description: '将 .md 文件复制到 .windsurf/rules/ 目录',
        path: '.windsurf/rules/'
      }
    };

    return JSON.stringify(configObj, null, 2);
  }

  protected getFileExtension(): string {
    return 'md';
  }

  protected getConfigFileName(): string {
    return 'windsurf-config.json';
  }

  protected supportsFlavorExport(): boolean {
    return true;
  }
}

// 注册适配器
globalAdapterRegistry.register(new WindsurfAdapter());
