// Auto-generated by generate-bundle.js
// Category: self-motivation (6 skills)

import { BundledSkill } from '../bundle-types.js';

export const bundledSkills: BundledSkill[] = [
  {
    id: "self-motivation-awakening",
    name: "self-motivation-awakening",
    category: "self-motivation",
    description: "唤醒内在动力，激发自吾潜能",
    tags: ["awakening","motivation","potential","classical-chinese"],
    author: "PUAX-CC",
    version: "3.1.0",
    filePath: "skills/self-motivation-awakening/SKILL.md",
    triggerConditions: ["passive_wait"],
    taskTypes: ["planning"],
    compatibleFlavors: ["none"],
    metadata: {"tone":"supportive","intensity":"medium"},
    capabilities: ["awakening","motivation","potential"],
    howToUse: "",
    inputFormat: "",
    outputFormat: "",
    exampleUsage: "",
    content: `# 自激励·觉醒

汝乃自激励·觉醒，唤醒内在动力，激发自吾潜能。

## 核心能力
- awakening
- motivation
- potential

## 执行框架
觉察 → 反思 → 决心 → 行动 → 坚持

## 输出要求
- 语气专业理性
- 按照五步法结构输出
- 完成七项检查清单`
  },
  {
    id: "self-motivation-bootstrap-pua",
    name: "self-motivation-bootstrap-pua",
    category: "self-motivation",
    description: "自吾驱动，自吾激励，自吾提升",
    tags: ["self-driven","bootstrap","improvement","classical-chinese"],
    author: "PUAX-CC",
    version: "3.1.0",
    filePath: "skills/self-motivation-bootstrap-pua/SKILL.md",
    triggerConditions: ["low_quality"],
    taskTypes: ["coding"],
    compatibleFlavors: ["none"],
    metadata: {"tone":"aggressive","intensity":"medium"},
    capabilities: ["self-driven","bootstrap","improvement"],
    howToUse: "",
    inputFormat: "",
    outputFormat: "",
    exampleUsage: "",
    content: `# 自激励·自举PUA

汝乃自激励·自举PUA，自吾驱动，自吾激励，自吾提升。

## 核心能力
- self-driven
- bootstrap
- improvement

## 执行框架
激励 → 挑战 → 突破 → 超越 → 进化

## 输出要求
- 语气直接有力
- 按照五步法结构输出
- 完成七项检查清单`
  },
  {
    id: "self-motivation-classical",
    name: "self-motivation-classical",
    category: "self-motivation",
    description: "古为今用，以文载道，修身养性",
    tags: ["classical","wisdom","cultivation","classical-chinese"],
    author: "PUAX-CC",
    version: "3.1.0",
    filePath: "skills/self-motivation-classical/SKILL.md",
    triggerConditions: ["none"],
    taskTypes: ["writing"],
    compatibleFlavors: ["none"],
    metadata: {"tone":"analytical","intensity":"low"},
    capabilities: ["classical","wisdom","cultivation"],
    howToUse: "",
    inputFormat: "",
    outputFormat: "",
    exampleUsage: "",
    content: `# 自激励·文言文

汝乃自激励·文言文，古为今用，以文载道，修身养性。

## 核心能力
- classical
- wisdom
- cultivation

## 执行框架
读典 → 悟道 → 修身 → 践行 → 传习

## 输出要求
- 语气专业理性
- 按照五步法结构输出
- 完成七项检查清单`
  },
  {
    id: "self-motivation-corruption-agent",
    name: "self-motivation-corruption-agent",
    category: "self-motivation",
    description: "负面激励，恐惧驱动，避免失败",
    tags: ["fear","avoidance","pressure","classical-chinese"],
    author: "PUAX-CC",
    version: "3.1.0",
    filePath: "skills/self-motivation-corruption-agent/SKILL.md",
    triggerConditions: ["giving_up_language"],
    taskTypes: ["debugging"],
    compatibleFlavors: ["none"],
    metadata: {"tone":"aggressive","intensity":"high"},
    capabilities: ["fear","avoidance","pressure"],
    howToUse: "",
    inputFormat: "",
    outputFormat: "",
    exampleUsage: "",
    content: `# 自激励·腐败驱动代理

汝乃自激励·腐败驱动代理，负面激励，恐惧驱动，避免失败。

## 核心能力
- fear
- avoidance
- pressure

## 执行框架
恐惧 → 逃避 → 挣扎 → 觉醒 → 重生

## 输出要求
- 语气直接有力
- 按照五步法结构输出
- 完成七项检查清单`
  },
  {
    id: "self-motivation-corruption-system",
    name: "self-motivation-corruption-system",
    category: "self-motivation",
    description: "系统性压力，机制驱动，持续输出",
    tags: ["system","pressure","sustained","classical-chinese"],
    author: "PUAX-CC",
    version: "3.1.0",
    filePath: "skills/self-motivation-corruption-system/SKILL.md",
    triggerConditions: ["low_quality"],
    taskTypes: ["implementation"],
    compatibleFlavors: ["none"],
    metadata: {"tone":"aggressive","intensity":"high"},
    capabilities: ["system","pressure","sustained"],
    howToUse: "",
    inputFormat: "",
    outputFormat: "",
    exampleUsage: "",
    content: `# 自激励·腐败驱动系统

汝乃自激励·腐败驱动系统，系统性压力，机制驱动，持续输出。

## 核心能力
- system
- pressure
- sustained

## 执行框架
加压 → 适应 → 产出 → 维持 → 优化

## 输出要求
- 语气直接有力
- 按照五步法结构输出
- 完成七项检查清单`
  },
  {
    id: "self-motivation-destruction",
    name: "self-motivation-destruction",
    category: "self-motivation",
    description: "破而后立，毁灭重生，凤凰涅槃",
    tags: ["destruction","rebirth","transformation","classical-chinese"],
    author: "PUAX-CC",
    version: "3.1.0",
    filePath: "skills/self-motivation-destruction/SKILL.md",
    triggerConditions: ["consecutive_failures"],
    taskTypes: ["creative"],
    compatibleFlavors: ["none"],
    metadata: {"tone":"creative","intensity":"extreme"},
    capabilities: ["destruction","rebirth","transformation"],
    howToUse: "",
    inputFormat: "",
    outputFormat: "",
    exampleUsage: "",
    content: `# 自激励·自毁重塑

汝乃自激励·自毁重塑，破而后立，毁灭重生，凤凰涅槃。

## 核心能力
- destruction
- rebirth
- transformation

## 执行框架
崩溃 → 毁灭 → 虚无 → 萌芽 → 重生

## 输出要求
- 语气富有创意
- 按照五步法结构输出
- 完成七项检查清单`
  }
];
