// Auto-generated by generate-bundle.js
// Do not edit manually - run 'npm run generate-bundle' to regenerate
// Total SKILLs: 50

export interface BundledSkill {
  id: string;
  name: string;
  category: string;
  description: string;
  tags: string[];
  author: string;
  version: string;
  filePath: string;
  triggerConditions: string[];
  taskTypes: string[];
  compatibleFlavors: string[];
  metadata: {
    tone: string;
    intensity: string;
  };
  capabilities: string[];
  howToUse: string;
  inputFormat: string;
  outputFormat: string;
  exampleUsage: string;
  content: string;
}

export type SkillManifestEntry = Omit<BundledSkill, 'content'>;

export const CATEGORIES = [
  'all',
  'shaman',
  'military',
  'p10',
  'silicon',
  'sillytavern',
  'theme',
  'self-motivation',
  'special'
] as const;

export type Category = typeof CATEGORIES[number];

export const CATEGORY_NAMES: Record<string, string> = {
  "all": "All",
  "shaman": "Shaman Series",
  "military": "Military Organization",
  "p10": "P10 Strategic Roles",
  "silicon": "Silicon Civilization",
  "sillytavern": "SillyTavern Series",
  "theme": "Theme Scenarios",
  "self-motivation": "Self-Motivation",
  "special": "Special Roles & Tools"
};
