// Auto-generated by generate-bundle.js
// Lazy-loading facade over per-category bundles

import {
  BundledSkill,
  CATEGORIES,
  CATEGORY_NAMES,
  Category,
  SkillManifestEntry
} from './bundle-types.js';

export type { BundledSkill, Category, SkillManifestEntry };
export { CATEGORIES, CATEGORY_NAMES };

const categoryLoaders: Record<string, () => BundledSkill[]> = {
  "shaman": () => require('./bundles/bundle-shaman').bundledSkills as BundledSkill[],
  "military": () => require('./bundles/bundle-military').bundledSkills as BundledSkill[],
  "p10": () => require('./bundles/bundle-p10').bundledSkills as BundledSkill[],
  "silicon": () => require('./bundles/bundle-silicon').bundledSkills as BundledSkill[],
  "sillytavern": () => require('./bundles/bundle-sillytavern').bundledSkills as BundledSkill[],
  "theme": () => require('./bundles/bundle-theme').bundledSkills as BundledSkill[],
  "self-motivation": () => require('./bundles/bundle-self-motivation').bundledSkills as BundledSkill[],
  "special": () => require('./bundles/bundle-special').bundledSkills as BundledSkill[],
  "dream": () => require('./bundles/bundle-dream').bundledSkills as BundledSkill[]
};

const loadedCategories = new Map<string, BundledSkill[]>();
const skillByIdCache = new Map<string, BundledSkill>();

function loadCategory(category: string): BundledSkill[] {
  if (loadedCategories.has(category)) {
    return loadedCategories.get(category)!;
  }

  const loader = categoryLoaders[category];
  if (!loader) {
    return [];
  }

  const skills = loader();
  loadedCategories.set(category, skills);
  for (const skill of skills) {
    skillByIdCache.set(skill.id, skill);
  }
  return skills;
}

function loadAllCategories(): void {
  for (const category of CATEGORIES) {
    loadCategory(category);
  }
}

let _manifest: SkillManifestEntry[] | null = null;
export function getSkillManifest(): SkillManifestEntry[] {
  if (!_manifest) {
    _manifest = require('./skill-manifest.js').SKILL_MANIFEST as SkillManifestEntry[];
  }
  return _manifest;
}

export const SKILL_MANIFEST: SkillManifestEntry[] = new Proxy([] as SkillManifestEntry[], {
  get(target, prop, receiver) {
    return Reflect.get(getSkillManifest(), prop, receiver);
  },
  has(target, prop) {
    return Reflect.has(getSkillManifest(), prop);
  },
  ownKeys() {
    return Reflect.ownKeys(getSkillManifest());
  },
  getOwnPropertyDescriptor(target, prop) {
    return Reflect.getOwnPropertyDescriptor(getSkillManifest(), prop);
  }
});

export function getManifestEntryById(id: string): SkillManifestEntry | undefined {
  return getSkillManifest().find(skill => skill.id === id);
}

export function getAllBundledSkills(): BundledSkill[] {
  loadAllCategories();
  return getSkillManifest().map(entry => skillByIdCache.get(entry.id)!);
}

function inferCategoryFromId(id: string): string | undefined {
  if (id === 'strategic-architect') return 'p10';
  const prefix = id.split('-')[0];
  if (CATEGORIES.includes(prefix as Category)) {
    return prefix;
  }
  if (id.startsWith('self-motivation-')) return 'self-motivation';
  return undefined;
}

export function getBundledSkillById(id: string): BundledSkill | undefined {
  if (skillByIdCache.has(id)) {
    return skillByIdCache.get(id);
  }

  const inferred = inferCategoryFromId(id);
  if (inferred) {
    loadCategory(inferred);
    if (skillByIdCache.has(id)) {
      return skillByIdCache.get(id);
    }
  }

  const manifestEntry = getManifestEntryById(id);
  if (!manifestEntry) {
    return undefined;
  }

  loadCategory(manifestEntry.category);
  return skillByIdCache.get(id);
}

export function getBundledSkillsByCategory(category: string): BundledSkill[] {
  if (category === 'all') {
    return getAllBundledSkills();
  }
  return loadCategory(category);
}

export function searchBundledSkills(keyword: string): BundledSkill[] {
  const lowerKeyword = keyword.toLowerCase();
  const matches = getSkillManifest().filter(skill =>
    skill.name.toLowerCase().includes(lowerKeyword) ||
    skill.description.toLowerCase().includes(lowerKeyword) ||
    skill.category.toLowerCase().includes(lowerKeyword) ||
    skill.tags.some(tag => tag.toLowerCase().includes(lowerKeyword)) ||
    skill.capabilities.some(cap => cap.toLowerCase().includes(lowerKeyword))
  );

  return matches
    .map(skill => getBundledSkillById(skill.id))
    .filter((skill): skill is BundledSkill => skill !== undefined);
}

export function getSkillCategories(): string[] {
  return [...new Set(getSkillManifest().map(skill => skill.category))].sort();
}

export function getSkillCountByCategory(): Record<string, number> {
  const count: Record<string, number> = {};
  for (const skill of getSkillManifest()) {
    count[skill.category] = (count[skill.category] || 0) + 1;
  }
  return count;
}

export const getAllBundledRoles = getAllBundledSkills;
export const getBundledRoleById = getBundledSkillById;
export const getBundledRolesByCategory = getBundledSkillsByCategory;
export const searchBundledRoles = searchBundledSkills;
export type BundledRole = BundledSkill;
