/**
 * 从 methodologies.yaml 生成类别方法论 Markdown 指南
 */

import type { Methodology, MethodologyStep, ChecklistItem } from './methodology-engine.js';

export interface CategoryGuideMeta {
  display_name?: string;
  framework?: string;
  metaphors?: {
    problem?: string;
    solution?: string;
    process?: string;
  };
  phrase_bank?: Record<string, string[]>;
}

export interface MethodologyYamlForGuide {
  base_methodology: Methodology;
  base_checklist: ChecklistItem[];
  role_methodologies: Record<string, {
    name: string;
    description: string;
    steps: MethodologyStep[];
  }>;
  category_methodologies: Record<string, {
    name: string;
    description: string;
    step_names?: string[];
    step_descriptions?: string[];
  }>;
  category_guides?: Record<string, CategoryGuideMeta>;
}

const CATEGORY_PREFIX: Record<string, string> = {
  military: 'military',
  shaman: 'shaman',
  p10: 'strategic-architect',
  silicon: 'silicon',
  sillytavern: 'sillytavern',
  theme: 'theme',
  'self-motivation': 'self-motivation',
  special: 'special',
};

const DEFAULT_DISPLAY_NAMES: Record<string, string> = {
  military: '军事类',
  shaman: '萨满/先知类',
  p10: 'P10 战略类',
  silicon: '硅基文明类',
  sillytavern: 'SillyTavern 类',
  theme: '主题场景类',
  'self-motivation': '自我激励类',
  special: '特色角色类',
};

function buildCategoryMethodology(category: string, data: MethodologyYamlForGuide): Methodology {
  const cat = data.category_methodologies[category];
  if (!cat) {
    throw new Error(`未知类别: ${category}`);
  }

  if (cat.step_names?.length) {
    return {
      name: cat.name,
      description: cat.description,
      steps: cat.step_names.map((name, index) => ({
        name,
        description: cat.step_descriptions?.[index] || cat.description,
        actions: [],
      })),
    };
  }

  return {
    name: cat.name,
    description: cat.description,
    steps: data.base_methodology.steps.map(step => ({ ...step, actions: [...step.actions] })),
  };
}

function enrichStepsFromRoles(
  category: string,
  steps: MethodologyStep[],
  data: MethodologyYamlForGuide
): MethodologyStep[] {
  const prefix = CATEGORY_PREFIX[category];
  const roleEntry = Object.entries(data.role_methodologies).find(([id]) =>
    prefix === 'strategic-architect' ? id === 'strategic-architect' : id.startsWith(`${prefix}-`)
  );

  if (!roleEntry) return steps;

  const [, roleMethod] = roleEntry;
  return steps.map((step, index) => {
    const roleStep = roleMethod.steps[index];
    if (!roleStep) return step;
    return {
      name: step.name || roleStep.name,
      description: step.description || roleStep.description,
      actions: roleStep.actions.length > 0 ? roleStep.actions : step.actions,
      checkpoint: roleStep.checkpoint || step.checkpoint,
    };
  });
}

function getCategoryMethodology(category: string, data: MethodologyYamlForGuide): Methodology {
  const base = buildCategoryMethodology(category, data);
  return {
    ...base,
    steps: enrichStepsFromRoles(category, base.steps, data),
  };
}

function listRolesInCategory(category: string, data: MethodologyYamlForGuide): string[] {
  const prefix = CATEGORY_PREFIX[category];
  if (!prefix) return [];

  if (prefix === 'strategic-architect') {
    return data.role_methodologies['strategic-architect'] ? ['strategic-architect'] : [];
  }

  return Object.keys(data.role_methodologies)
    .filter(id => id.startsWith(`${prefix}-`))
    .sort();
}

function renderPhraseBank(phraseBank: Record<string, string[]> | undefined): string {
  if (!phraseBank) return '';

  const labels: Record<string, string> = {
    opening: '开场白',
    progress: '进行中',
    difficulty: '遇到困难',
    victory: '取得胜利',
    motivate: '督促激励',
  };

  let out = '## 通用话术库\n\n';
  for (const [key, phrases] of Object.entries(phraseBank)) {
    out += `### ${labels[key] || key}\n`;
    for (const phrase of phrases) {
      out += `- ${phrase}\n`;
    }
    out += '\n';
  }
  return out;
}

export function generateCategoryGuideMarkdown(
  category: string,
  data: MethodologyYamlForGuide,
  generatedAt = new Date().toISOString()
): string {
  const guide = data.category_guides?.[category];
  const displayName = guide?.display_name || DEFAULT_DISPLAY_NAMES[category] || category;
  const methodology = getCategoryMethodology(category, data);
  const catMeta = data.category_methodologies[category];
  const roleIds = listRolesInCategory(category, data);

  let md = `<!-- AUTO-GENERATED by npm run generate-guides -->\n`;
  md += `<!-- Source: puax-mcp-server/src/data/methodologies.yaml -->\n`;
  md += `<!-- Generated at: ${generatedAt} -->\n\n`;
  md += `# ${displayName}角色方法论指南\n\n`;
  md += `## 概述\n\n`;

  if (guide?.framework && guide.metaphors) {
    md += `${displayName}角色采用**${guide.framework}**：\n`;
    md += `- 问题 = ${guide.metaphors.problem || '障碍'}\n`;
    md += `- 解决 = ${guide.metaphors.solution || '胜利'}\n`;
    md += `- 调试过程 = ${guide.metaphors.process || methodology.name}\n\n`;
  } else {
    md += `${catMeta.description}（**${catMeta.name}**）\n\n`;
  }

  md += `## 五步法框架\n\n`;
  methodology.steps.forEach((step, index) => {
    md += `### Step ${index + 1}: ${step.name}\n`;
    md += `${step.description}\n\n`;
    if (step.actions.length > 0) {
      md += `**核心行动**:\n`;
      step.actions.forEach((action, i) => {
        md += `${i + 1}. ${action}\n`;
      });
      md += '\n';
    }
    if (step.checkpoint) {
      md += `**检查点**: ${step.checkpoint}\n\n`;
    }
    md += '---\n\n';
  });

  if (roleIds.length > 0) {
    md += `## 角色差异化（${roleIds.length} 个）\n\n`;
    for (const roleId of roleIds) {
      const role = data.role_methodologies[roleId];
      if (!role) continue;
      md += `### ${role.name} (\`${roleId}\`)\n`;
      md += `- **描述**: ${role.description}\n`;
      if (role.steps[0]?.actions[0]) {
        md += `- **首步行动**: ${role.steps[0].actions[0]}\n`;
      }
      md += '\n';
    }
  }

  md += renderPhraseBank(guide?.phrase_bank);

  md += `## 强制检查清单\n\n`;
  md += `> 与 MCP 方法论引擎 base_checklist 同步\n\n`;
  for (const item of data.base_checklist) {
    md += `- [ ] **${item.text}**`;
    if (item.description) md += ` — ${item.description}`;
    md += '\n';
  }

  md += `\n## 维护说明\n\n`;
  md += `请勿手工编辑本文件。修改 \`puax-mcp-server/src/data/methodologies.yaml\` 后运行：\n\n`;
  md += `\`\`\`bash\ncd puax-mcp-server && npm run generate-guides\n\`\`\`\n`;

  return md;
}

export function listGuideCategories(data: MethodologyYamlForGuide): string[] {
  return Object.keys(data.category_methodologies).sort();
}

export function generateAllCategoryGuides(
  data: MethodologyYamlForGuide,
  generatedAt?: string
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const category of listGuideCategories(data)) {
    out[category] = generateCategoryGuideMarkdown(category, data, generatedAt);
  }
  return out;
}
