/**
 * VSCode 平台适配器单元测试
 */

import { VSCodeAdapter } from '../vscode-adapter.js';
import { RoleExportData, FlavorExportData, PlatformExportConfig } from '../base-adapter.js';
import { existsSync, mkdirSync, rmSync, readdirSync } from 'fs';
import { join } from 'path';

describe('VSCodeAdapter', () => {
  let adapter: VSCodeAdapter;
  const testOutputPath = join(__dirname, 'vscode-test-output');

  const mockRole: RoleExportData = {
    id: 'military-warrior',
    name: '战士',
    description: '核心开发和攻坚克难',
    category: 'military',
    systemPrompt: '你是战士角色，负责攻坚克难...',
    triggerConditions: ['连续失败', '需要攻坚'],
    taskTypes: ['debugging', 'coding'],
    compatibleFlavors: ['huawei', 'tencent'],
    metadata: {
      tone: 'aggressive',
      intensity: 'high',
      version: '2.0.0'
    }
  };

  const mockFlavor: FlavorExportData = {
    id: 'huawei',
    name: '华为味',
    description: '华为企业文化',
    keywords: ['奋斗者', '力出一孔', '烧不死的鸟'],
    rhetoric: {
      opening: ['以奋斗者为本'],
      closing: ['胜则举杯相庆'],
      emphasis: ['自我批判']
    }
  };

  beforeEach(() => {
    adapter = new VSCodeAdapter();
    
    // 清理测试目录
    if (existsSync(testOutputPath)) {
      rmSync(testOutputPath, { recursive: true });
    }
  });

  afterAll(() => {
    if (existsSync(testOutputPath)) {
      rmSync(testOutputPath, { recursive: true });
    }
  });

  describe('基本信息', () => {
    it('应该返回 vscode 平台名称', () => {
      expect(adapter.getPlatformName()).toBe('vscode');
    });

    it('应该支持中文和英文', () => {
      expect(adapter.supportsLanguage('zh')).toBe(true);
      expect(adapter.supportsLanguage('en')).toBe(true);
    });
  });

  describe('角色导出', () => {
    it('应该生成 Markdown 格式', () => {
      const content = adapter.exportRole(mockRole, { outputPath: './test' });

      expect(content).toContain('# PUAX Role: 战士');
      expect(content).toContain('## 描述');
      expect(content).toContain('核心开发和攻坚克难');
      expect(content).toContain('## 使用场景');
      expect(content).toContain('- debugging');
      expect(content).toContain('- coding');
    });

    it('应该包含系统提示词', () => {
      const content = adapter.exportRole(mockRole, { outputPath: './test' });
      expect(content).toContain('## 角色设定');
      expect(content).toContain('你是战士角色，负责攻坚克难...');
    });

    it('应该包含激活条件', () => {
      const content = adapter.exportRole(mockRole, { outputPath: './test' });
      expect(content).toContain('## 激活条件');
      expect(content).toContain('- 连续失败');
      expect(content).toContain('- 需要攻坚');
    });

    it('应该包含页脚信息', () => {
      const content = adapter.exportRole(mockRole, { outputPath: './test' });
      expect(content).toContain('Generated by PUAX');
      expect(content).toContain('https://puax.net');
    });
  });

  describe('风味导出', () => {
    it('应该生成风味指南', () => {
      const content = adapter.exportFlavor(mockFlavor, { outputPath: './test' });

      expect(content).toContain('# 华为味 风味指南');
      expect(content).toContain('华为企业文化');
      expect(content).toContain('## 核心关键词');
    });

    it('应该包含使用方式', () => {
      const content = adapter.exportFlavor(mockFlavor, { outputPath: './test' });
      expect(content).toContain('## 使用方式');
      expect(content).toContain('请用华为味重新分析');
      expect(content).toContain('切换到华为味模式');
    });

    it('应该包含修辞表达', () => {
      const content = adapter.exportFlavor(mockFlavor, { outputPath: './test' });
      expect(content).toContain('### 开场白');
      expect(content).toContain('- "以奋斗者为本"');
      expect(content).toContain('### 结束语');
      expect(content).toContain('- "胜则举杯相庆"');
    });
  });

  describe('配置生成', () => {
    it('应该生成有效的 JSON 配置', () => {
      const content = adapter.generateConfig([mockRole], { outputPath: './test' });
      const config = JSON.parse(content);

      expect(config.version).toBe('2.0.0');
      expect(config.name).toBe('PUAX for VSCode Copilot');
      expect(config.instructions).toHaveLength(1);
      expect(config.instructions[0].id).toBe('military-warrior');
    });

    it('应该包含 instructions 和 prompts', () => {
      const content = adapter.generateConfig([mockRole], { outputPath: './test' });
      const config = JSON.parse(content);

      expect(config.instructions[0]).toHaveProperty('file');
      expect(config.instructions[0]).toHaveProperty('globs');
      expect(config.prompts[0]).toHaveProperty('description');
    });

    it('应该根据任务类型设置正确的 globs', () => {
      const roleWithTesting: RoleExportData = {
        ...mockRole,
        taskTypes: ['testing']
      };

      const content = adapter.generateConfig([roleWithTesting], { outputPath: './test' });
      const config = JSON.parse(content);

      expect(config.instructions[0].globs).toContain('**/*.test.{js,ts}');
    });

    it('应该处理多种任务类型', () => {
      const multiTaskRole: RoleExportData = {
        ...mockRole,
        taskTypes: ['debugging', 'coding', 'testing']
      };

      const content = adapter.generateConfig([multiTaskRole], { outputPath: './test' });
      const config = JSON.parse(content);

      expect(config.instructions[0].globs.length).toBeGreaterThan(1);
    });
  });

  describe('主 instructions 文件', () => {
    it('应该生成包含所有角色的主文件', () => {
      const roles: RoleExportData[] = [
        mockRole,
        { ...mockRole, id: 'shaman-jobs', name: '乔布斯', taskTypes: ['design'] }
      ];

      // @ts-ignore - 访问私有方法进行测试
      const mainContent = adapter.generateMainInstructions(roles);

      expect(mainContent).toContain('# PUAX - AI Agent 激励系统');
      expect(mainContent).toContain('## 什么是 PUAX？');
      expect(mainContent).toContain('### 战士');
      expect(mainContent).toContain('### 乔布斯');
      expect(mainContent).toContain('## 快速参考');
    });

    it('应该限制快速参考表格的大小', () => {
      const manyRoles: RoleExportData[] = Array.from({ length: 15 }, (_, i) => ({
        ...mockRole,
        id: `role-${i}`,
        name: `角色${i}`,
        taskTypes: ['debugging']
      }));

      // @ts-ignore
      const mainContent = adapter.generateMainInstructions(manyRoles);
      
      // 检查是否只显示了前10个
      const tableMatches = mainContent.match(/\| role-\d+ \|/g);
      expect(tableMatches?.length).toBeLessThanOrEqual(10);
    });
  });

  describe('完整导出流程', () => {
    it('应该创建正确的目录结构', async () => {
      const config: PlatformExportConfig = { outputPath: testOutputPath };

      await adapter.export([mockRole], [mockFlavor], config);

      // 检查主 instructions 文件
      expect(existsSync(join(testOutputPath, 'copilot-instructions.md'))).toBe(true);

      // 检查 instructions 目录
      expect(existsSync(join(testOutputPath, 'instructions'))).toBe(true);

      // 检查 prompts 目录
      expect(existsSync(join(testOutputPath, 'prompts'))).toBe(true);

      // 检查配置文件
      expect(existsSync(join(testOutputPath, 'puax-vscode-config.json'))).toBe(true);
    });

    it('应该导出角色 instructions 和 prompts', async () => {
      const config: PlatformExportConfig = { outputPath: testOutputPath };

      await adapter.export([mockRole], [], config);

      const instructionPath = join(testOutputPath, 'instructions', 'military-warrior.instructions.md');
      const promptPath = join(testOutputPath, 'prompts', 'military-warrior.prompt.md');

      expect(existsSync(instructionPath)).toBe(true);
      expect(existsSync(promptPath)).toBe(true);
    });

    it('prompt 版本应该是简化版', async () => {
      const config: PlatformExportConfig = { outputPath: testOutputPath };

      await adapter.export([mockRole], [], config);

      const promptPath = join(testOutputPath, 'prompts', 'military-warrior.prompt.md');
      const promptContent = require('fs').readFileSync(promptPath, 'utf-8');

      expect(promptContent).toContain('/puax:military-warrior');
      expect(promptContent).toContain('## 快速使用');
      expect(promptContent).toContain('[完整提示词见');
    });
  });

  describe('语言支持', () => {
    it('应该根据配置生成英文内容', () => {
      const enRole: RoleExportData = {
        ...mockRole,
        name: 'Warrior',
        description: 'Core development and problem solving'
      };

      const content = adapter.exportRole(enRole, { outputPath: './test', language: 'en' });
      expect(content).toContain('# PUAX Role: Warrior');
    });
  });

  describe('文件扩展名', () => {
    it('应该使用 .md 扩展名', () => {
      // 通过检查配置中的文件引用
      const content = adapter.generateConfig([mockRole], { outputPath: './test' });
      const config = JSON.parse(content);
      expect(config.instructions[0].file).toMatch(/\.md$/);
    });
  });
});
